# Generated by Django 4.2.7 on 2023-12-06 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0004_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
